services:
  app:
    container_name: timelove-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis

  db:
    container_name: timelove-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: victor1032
      POSTGRES_DB: timelove
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: timelove-redis
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  pgdata: