version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: victor1032
      POSTGRES_DB: timelove
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: